from typing import Literal

from pydantic import BaseModel, Field

# Yosys JSON netlist format: https://github.com/YosysHQ-Docs/yosys-cmd-ref/blob/main/source/cmd/write_json.rst

# Bit vector: ints are net IDs, strings are constants ("0", "1", "x", "z")
Bits = list[int | str]


class Port(BaseModel):
    direction: Literal["input", "output", "inout"]
    bits: Bits


class Cell(BaseModel):
    # 1 = name is auto-generated by Yosys, 0 = user-defined
    hide_name: int
    type: str
    # Parameter values are binary bit-vector strings, e.g. "00000001"
    parameters: dict[str, str]
    port_directions: dict[str, Literal["input", "output", "inout"]] = Field(default_factory=dict)
    connections: dict[str, Bits]


class Module(BaseModel):
    ports: dict[str, Port]
    cells: dict[str, Cell]


class Netlist(BaseModel):
    creator: str
    modules: dict[str, Module]
